### ISSUE TITLE
Not being detected by blesta

### ISSUE THREAD

**Issue by GreenArrowlol** [wirecatllc/blesta-stripe-universal#3]
Hey I added it to the right directory and cross checked but it isn't being detected in the payment gateways option

what did I do wrong?
![image](https://github.com/wirecatllc/blesta-stripe-universal/assets/76021102/92097ac7-d54c-4c79-89a9-d68f31ad6539)
![image](https://github.com/wirecatllc/blesta-stripe-universal/assets/76021102/714d8d77-8a3e-40a4-9cc1-5eca5e077eee)

**Comment by NeverBehave** [comment]
Try renaming the directory to `stripe_universal`, readme updated.

**Comment by GreenArrowlol** [comment]
great worked and I did my first test charge and this showed up
![image](https://github.com/wirecatllc/blesta-stripe-universal/assets/76021102/ef4c869f-33de-4107-bffd-c408752b7e6d)

but I don't see it on my list (the one in pic is a old transaction)
![image](https://github.com/wirecatllc/blesta-stripe-universal/assets/76021102/61c7378d-adfa-4d0a-b219-11d082772102)

**Comment by NeverBehave** [comment]
Didn't tested with different currency but should be fine. Try capture the log and open a different issue.
