### ISSUE TITLE
How to change the stripe universal text?

### ISSUE THREAD

**Issue by GreenArrowlol** [wirecatllc/blesta-stripe-universal#6]
I'd like it to show up as Stripe (CreditCard/DebitCard)

How do I change the text?

**Comment by NeverBehave** [comment]
Not entirely sure if this would work: https://github.com/wirecatllc/blesta-stripe-universal/blob/0cb52bb680ce9661cedda8ad190da91e822cb093/language/en_us/stripe_universal.php#L20
